name: Test GCP Authentication

on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: 'GCP Project ID'
        required: true
        type: string

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
          project_id: ${{ inputs.gcp_project_id }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Authentication
        run: |
          gcloud auth list
          gcloud config list project
