# .github/workflows/gcp-login-and-list.yml

name: GCP Login and List Instances

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
      gcp_credentials:
        required: true
        type: string

jobs:
  list-instances:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.gcp_project_id }}
          service_account_key: ${{ inputs.gcp_credentials }}

      - name: Authenticate with GCP
        run: |
          echo "${{ inputs.gcp_credentials }}" > "${{ github.workspace }}/key.json"
          gcloud auth activate-service-account --key-file="${{ github.workspace }}/key.json"
          gcloud config set project ${{ inputs.gcp_project_id }}

      - name: List Compute Engine instances
        run: |
          echo "Fetching Compute Engine instances in project ${{ inputs.gcp_project_id }}"
          gcloud compute instances list || echo "No instances found"
