name: GCP Login and List Instances

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
    secrets:
      gcp_credentials:
        required: true
    outputs:
      instance_output:
        description: "List of GCP instances"
        value: ${{ jobs.list-instances.outputs.instance_output }}

jobs:
  list-instances:
    runs-on: ubuntu-latest
    outputs:
      instance_output: ${{ steps.capture-output.outputs.instances }}

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.gcp_project_id }}

      - name: List Compute Engine instances and capture output
        id: capture-output
        run: |
          instances=$(gcloud compute instances list --format="json" || echo "[]")
          echo "instances<<EOF" >> $GITHUB_OUTPUT
          echo "$instances" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
