name: Call Pub/Sub Test Workflow

on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: 'GCP Project ID'
        required: true
        type: string
      bucket_region:
        description: 'Region for the bucket (e.g. us-central1)'
        required: false
        default: 'us-central1'
        type: string
      pubsub_topic:
        description: 'Pub/Sub Topic'
        required: true
        type: string
        default: 'test-topic'
      pubsub_subscription:
        description: 'Pub/Sub Subscription'
        required: true
        type: string
        default: 'test-subscription'

jobs:
  call-reusable-pubsub:
    uses: ./.github/workflows/reusable-gcp-pubsub-test.yml
    with:
      gcp_project_id: ${{ inputs.gcp_project_id }}
      pubsub_topic_id: ${{ inputs.pubsub_topic }}
      pubsub_subscription_id: ${{ inputs.pubsub_subscription }}
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
