name: Test Pub/Sub with Dataflow

on:
  push:
    branches: [main]

jobs:
  test-dataflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install "apache-beam[gcp]"

      - name: Run Dataflow Job
        run: |
          source venv/bin/activate
          python dataflow_pipeline.py
