name: Test Pub/Sub Dataflow

on:
  workflow_dispatch:

jobs:
  test-dataflow:
    uses: ./.github/workflows/rusable-dataflow-deploy.yaml
    with:
      dataflow_path: dataflows/pubsub
      job_name: test-pubsub-${{ github.run_number }}
      pubsub_topic: test-pubsub
    secrets: inherit
