name: Test Pub/Sub Dataflow

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
      pubsub_topic_id:
        required: true
        type: string
      pubsub_subscription_id:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  test-dataflow:
    uses: ./.github/workflows/reusable-dataflow-deploy.yml
    with:
      dataflow_path: ${{ inputs.dataflow_path }}
      job_name: ${{ inputs.job_name }}
      pubsub_topic: ${{ inputs.pubsub_topic }}
    secrets: inherit
