name: Test Pub/Sub Dataflow

on:
  workflow_dispatch:
    inputs:
      dataflow_path:
        required: false
        type: string
        default: 'dataflow/pubsub/'
      job_name:
        required: false
        type: string
        default: 'pubsub-dataflow'
      pubsub_topic:
        required: false
        type: string
        default: 'pubsub-test'

jobs:
  test-dataflow:
    uses: ./.github/workflows/reusable-dataflow-deploy.yml
    secrets: inherit
