name: Use GCP Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-login-and-list:
    uses: ./.github/workflows/gcp-login-and-list.yml
    with:
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}  # OR hardcode the ID here
    secrets:
      gcp_credentials: ${{ secrets.GCP_SA_KEY }}

  print-instances:
    needs: call-login-and-list
    runs-on: ubuntu-latest
    steps:
      - name: Print instance info
        run: |
          echo "Available instances:"
          echo '${{ needs.call-login-and-list.outputs.instance_output }}' | jq .
